inherit_from: https://raw.githubusercontent.com/leanpanda-com/rubocop/master/rubocop-rspec.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - "bin/**/*"
    - ".bundle/**/*"
    - "bundle/**/*"

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/ModuleFunction:
  EnforcedStyle: module_function

RSpec/MultipleExpectations:
  Max: 2
